### ISSUE TITLE
python tip

### ISSUE THREAD

**Issue by dromer** [nberr/juce-template#3]
Don't use logical operators on strings. use f-strings instead :)

(can do a PR if you want. it just hurts me to see `+` used on strings :#)

**Comment by nberr** [comment]
A PR would be appreciated! I'm not so familiar with python so thanks for the tip!

**Comment by dromer** [comment]
See https://github.com/nberr/juce-template/pull/4

**Comment by nberr** [comment]
thanks for the python tip :)
